SIDDHANT SINHA

25070123109

EXP9: Study of Numpy Library

NumPy

Create Arrays

Perform Numeric Operations

In [ ]:
# Why NumPy?
# Faster than lists
# Used for numerical computation

In [38]:
#Declaration of NumPy
import numpy as np                               # as np is used so that we can call it by short name which you can decide by your own

a = np.array([1,10,20,30,40,50,500])             # command to call matrix is numpy.array
b = np.array([[1,2,3],[4,5,6]])                  # stored in list therefore printing of matrix usinh numpy library
print(a)
print(b)

#Dimension of Array
print(a.ndim)                                   # 1 dimentional
print(b.ndim)                                   # 2 dimentional

#Size oe shape or number of rows and columns
print(a.shape)                                  # Tells number of rows and columns
print(b.shape)

#Datatype
print(a.dtype)                                 # Tells us about the Data type
print(b.dtype)

#In-Built functions using NumPy
print(np.zeros((2,3)))                         # generates a matrix with 2 rows and 3 columns having all elements as 0
print()                                        # just used to give gap between 2
print(np.ones((3,3)))                          # generates a matrix with 3 rows and 3 columns having all elements as 1


print()
print(np.eye((3)))                            # Identity Matrix
print()

print(np.arange(1,10,2))
print(np.linspace(0,1,4))                     # generates equally spaced matrix i.e (ending-start)/n-1 i.e (1-0)/(4-1)
print()

print(b * 2)                                  # multiplies b matrix with 2
print()
print(a + 5)                                  # adds 5 to all the elemets of matrix a

print(np.mean(a))                             # calculate the mean of matrix a
print(np.median(a))                           # calculate the median of matrix a

print(np.max(a))                              # calculate the maximum of matrix a
print(np.min(a))                              # calculate the minimum of matrix a

print(np.sum(a))                              # calculate the sum of matrix a


[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]
1
2
(7,)
(2, 3)
int64
int64
[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[1 3 5 7 9]
[0.         0.33333333 0.66666667 1.        ]

[[ 2  4  6]
 [ 8 10 12]]

[  6  15  25  35  45  55 505]
93.0
30.0
500
1
651
